/**
 * Extraits de code réel, une source par archétype de langage (Grand Rewrite,
 * src/engine/constants.ts LANGUE_IDS). Généré par
 * scripts/fetch-code-samples.mjs — ne pas éditer à la main, relancer le
 * script pour rafraîchir. Mélangé aux blagues de terminalLines.ts dans
 * Terminal.svelte (visual-identity.md) pour donner au buffer l'air d'un vrai
 * projet, tout en gardant l'humour, différenciateur du jeu (PLAN.md §6).
 *
 * Attribution (dépôts publics permissifs, cf. THIRD_PARTY_NOTICES.md) :
 * - rust : rust-lang/rust (MIT OR Apache-2.0) — library/core/src/option.rs, library/core/src/result.rs
 * - python : django/django (BSD-3-Clause) — django/utils/text.py, django/core/paginator.py
 * - javascript : facebook/react (MIT) — packages/shared/shallowEqual.js, packages/react/src/ReactHooks.js
 *
 * 'none' (avant le premier Grand Rewrite) réutilise le pool javascript : les
 * deux partagent le même nom de fichier d'onglet (main.js), cf.
 * langueLabels.ts LANGUE_FILE_NAME.
 */
import type { LangueId } from "../engine/constants";

const RUST_CODE: readonly string[] = [
  "use crate::clone::TrivialClone;",
  "use crate::iter::{self, FusedIterator, TrustedLen};",
  "use crate::marker::Destruct;",
  "use crate::num::NonZero;",
  "use crate::ops::{self, ControlFlow, Deref, DerefMut, Residual, Try};",
  "use crate::panicking::{panic, panic_display};",
  "use crate::pin::Pin;",
  "use crate::{cmp, convert, hint, mem, slice};",
  "pub enum Option<T> {",
  "impl<T> Option<T> {",
  "    pub const fn is_some(&self) -> bool {",
  "        matches!(*self, Some(_))",
  "        match self {",
  "            None => false,",
  "            Some(x) => f(x),",
  "    pub const fn is_none(&self) -> bool {",
  "        !self.is_some()",
  "            None => true,",
  "    pub const fn as_ref(&self) -> Option<&T> {",
  "        match *self {",
  "            Some(ref x) => Some(x),",
  "            None => None,",
  "    pub const fn as_mut(&mut self) -> Option<&mut T> {",
  "            Some(ref mut x) => Some(x),",
  "    pub const fn as_pin_ref(self: Pin<&Self>) -> Option<Pin<&T>> {",
  "        match Pin::get_ref(self).as_ref() {",
  "            Some(x) => unsafe { Some(Pin::new_unchecked(x)) },",
  "    pub const fn as_pin_mut(self: Pin<&mut Self>) -> Option<Pin<&mut T>> {",
  "/// The `Option` type. See [the module level documentation](self) for more.",
  "    /// No value.",
  "    /// Some value of type `T`.",
  "// Type implementation",
  "    // Querying the contained values",
  "    /// Returns `true` if the option is a [`Some`] value.",
  "    /// # Examples",
  "    /// ```",
  "use crate::iter::{self, FusedIterator, TrustedLen};",
  "use crate::marker::Destruct;",
  "use crate::ops::{self, ControlFlow, Deref, DerefMut};",
  "use crate::{convert, fmt, hint};",
  "pub enum Result<T, E> {",
  "impl<T, E> Result<T, E> {",
  "    pub const fn is_ok(&self) -> bool {",
  "        matches!(*self, Ok(_))",
  "    pub const fn is_ok_and<F>(self, f: F) -> bool",
  "        F: [const] FnOnce(T) -> bool + [const] Destruct,",
  "        T: [const] Destruct,",
  "        E: [const] Destruct,",
  "        match self {",
  "            Err(_) => false,",
  "            Ok(x) => f(x),",
  "    pub const fn is_err(&self) -> bool {",
  "        !self.is_ok()",
  "    pub const fn is_err_and<F>(self, f: F) -> bool",
  "        F: [const] FnOnce(E) -> bool + [const] Destruct,",
  "            Ok(_) => false,",
  "            Err(e) => f(e),",
  "    pub const fn ok(self) -> Option<T>",
  "            Ok(x) => Some(x),",
  "            Err(_) => None,",
  "    pub const fn err(self) -> Option<E>",
  "            Ok(_) => None,",
  "            Err(x) => Some(x),",
  "    pub const fn as_ref(&self) -> Result<&T, &E> {",
  "// Do NOT add link reference definitions for `err` or `ok`, because they",
  "// will generate numerous incorrect URLs for `Err` and `Ok` elsewhere, due",
  "// to case folding.",
  "/// See the [module documentation](self) for details.",
  "    /// Contains the success value",
  "    /// Contains the error value",
  "// Type implementation",
  "    // Querying the contained values",
];

const PYTHON_CODE: readonly string[] = [
  "import gzip",
  "import re",
  "import secrets",
  "import textwrap",
  "import unicodedata",
  "from collections import deque",
  "from gzip import GzipFile",
  "from gzip import compress as gzip_compress",
  "from html import escape",
  "from html.parser import HTMLParser",
  "from io import BytesIO",
  "from django.core.exceptions import SuspiciousFileOperation",
  "from django.utils.functional import (",
  "    SimpleLazyObject,",
  "    cached_property,",
  "    keep_lazy_text,",
  "from django.utils.regex_helper import _lazy_re_compile",
  "from django.utils.translation import gettext as _",
  "from django.utils.translation import gettext_lazy, pgettext",
  "@keep_lazy_text",
  "def capfirst(x):",
  "    \"\"\"Capitalize the first letter of a string.\"\"\"",
  "    if not x:",
  "        return x",
  "    if not isinstance(x, str):",
  "        x = str(x)",
  "    return x[0].upper() + x[1:]",
  "re_newlines = _lazy_re_compile(r\"\\r\\n|\\r\")  # Used in normalize_newlines",
  "# Set up regular expressions",
  "        # If `text` ends with a newline, preserve it.",
  "    # The truncation text didn't contain the %(truncated_text)s string",
  "    # replacement argument so just append it to the text.",
  "        # in this.",
  "            # opened tag (LIFO). This avoids O(n) linear scans for unmatched",
  "            # end tags if `deque.remove()` would be called.",
  "            # No data was handled.",
  "import collections.abc",
  "import inspect",
  "import warnings",
  "from math import ceil",
  "from asgiref.sync import sync_to_async",
  "from django.utils.deprecation import RemovedInDjango70Warning",
  "from django.utils.functional import cached_property",
  "from django.utils.inspect import method_has_no_args",
  "from django.utils.translation import gettext_lazy as _",
  "class UnorderedObjectListWarning(RuntimeWarning):",
  "class InvalidPage(Exception):",
  "class PageNotAnInteger(InvalidPage):",
  "class EmptyPage(InvalidPage):",
  "class BasePaginator:",
  "    ELLIPSIS = _(\"…\")",
  "    default_error_messages = {",
  "        \"invalid_page\": _(\"That page number is not an integer\"),",
  "        \"min_page\": _(\"That page number is less than 1\"),",
  "        \"no_results\": _(\"That page contains no results\"),",
  "    def __init__(",
  "        object_list,",
  "        per_page,",
  "        orphans=0,",
  "        allow_empty_first_page=True,",
  "        error_messages=None,",
  "        self.object_list = object_list",
  "        self._check_object_list_is_ordered()",
  "        self.per_page = int(per_page)",
  "    # range generated by paginators, e.g. [1, 2, '…', 5, 6, 7, '…', 9, 10].",
  "            # RemovedInDjango70Warning: When the deprecation ends, replace",
  "            # with:",
  "            # raise ValueError(",
  "            #     \"per_page argument.\"",
  "        # it won't be a database hit per __getitem__.",
  "        # Special case, return zero if no items.",
  "        # Special case for the last page because there can be orphans.",
];

const JAVASCRIPT_CODE: readonly string[] = [
  "import is from './objectIs';",
  "import hasOwnProperty from './hasOwnProperty';",
  " * Returns true when the values of all keys are strictly equal.",
  "function shallowEqual(objA: mixed, objB: mixed): boolean {",
  "  if (is(objA, objB)) {",
  "    return true;",
  "    typeof objA !== 'object' ||",
  "    objA === null ||",
  "    typeof objB !== 'object' ||",
  "    objB === null",
  "    return false;",
  "  const keysA = Object.keys(objA);",
  "  const keysB = Object.keys(objB);",
  "  if (keysA.length !== keysB.length) {",
  "  for (let i = 0; i < keysA.length; i++) {",
  "    const currentKey = keysA[i];",
  "      !hasOwnProperty.call(objB, currentKey) ||",
  "      !is(objA[currentKey], objB[currentKey])",
  "      return false;",
  "  return true;",
  "export default shallowEqual;",
  "  // Test for A's keys different from B.",
  "      // $FlowFixMe[incompatible-use] lost refinement of `objB`",
  "import type {Dispatcher} from 'react-reconciler/src/ReactInternalTypes';",
  "import type {",
  "  ReactContext,",
  "  StartTransitionOptions,",
  "  Usable,",
  "  Awaited,",
  "} from 'shared/ReactTypes';",
  "import {REACT_CONSUMER_TYPE} from 'shared/ReactSymbols';",
  "import ReactSharedInternals from 'shared/ReactSharedInternals';",
  "type BasicStateAction<S> = (S => S) | S;",
  "type Dispatch<A> = A => void;",
  "function resolveDispatcher() {",
  "  const dispatcher = ReactSharedInternals.H;",
  "  if (__DEV__) {",
  "    if (dispatcher === null) {",
  "      console.error(",
  "          ' one of the following reasons:\\n' +",
  "          '2. You might be breaking the Rules of Hooks\\n' +",
  "  return dispatcher as any as Dispatcher;",
  "export function getCacheForType<T>(resourceType: () => T): T {",
  "  const dispatcher = ReactSharedInternals.A;",
  "  if (!dispatcher) {",
  "    return resourceType();",
  "  return dispatcher.getCacheForType(resourceType);",
  "export function useContext<T>(Context: ReactContext<T>): T {",
  "  const dispatcher = resolveDispatcher();",
  "    if (Context.$$typeof === REACT_CONSUMER_TYPE) {",
  "          'Did you mean to call useContext(Context) instead?',",
  "  // Will result in a null access error if accessed outside render phase. We",
  "  // intentionally don't throw our own error because this is in a hot path.",
  "  // Also helps ensure this is inlined.",
  "    // If there is no dispatcher, then we treat this as not being cached.",
  "  // $FlowFixMe[not-a-function] This is unstable, thus optional",
];

export const CODE_SAMPLES: Record<LangueId, readonly string[]> = {
  none: JAVASCRIPT_CODE,
  rust: RUST_CODE,
  python: PYTHON_CODE,
  javascript: JAVASCRIPT_CODE,
};

/** Attribution affichée en jeu (onglet README.md, cf. EditorView.svelte). */
export const CODE_SAMPLE_SOURCE: Record<LangueId, { repo: string; url: string }> = {
  none: { repo: "facebook/react", url: "https://github.com/facebook/react" },
  rust: { repo: "rust-lang/rust", url: "https://github.com/rust-lang/rust" },
  python: { repo: "django/django", url: "https://github.com/django/django" },
  javascript: { repo: "facebook/react", url: "https://github.com/facebook/react" },
};
